### ISSUE TITLE
Request failed with status code 404

### ISSUE THREAD

**Issue by mlavio829** [CodeZombie/TypeRip#10]
Seem to get an error when typing in a font: Request failed with status code 404

**Comment by mlavio829** [comment]
Sorry I realized I was typing in the name and not the URL. 
When I type in the URL (like your example:): https://fonts.adobe.com/fonts/jaf-herb
I get a network error

**Comment by CodeZombie** [comment]
This happens occasionally when the CORS proxy goes down. 
Looks like its back up now though, give it a try again and let me know if it works or not.

**Comment by CodeZombie** [comment]
Switched CORS proxies, this should (hopefully) no longer be an issue.

**Comment by kdotdot** [comment]
> Switched CORS proxies, this should (hopefully) no longer be an issue.

Hi, I am trying to process a font but it does still throw a Network Error atm
