### ISSUE TITLE
Request: Download all & Font Pack URL parsing

### ISSUE THREAD

**Issue by darvell** [CodeZombie/TypeRip#12]
A button to pull all files either in to a ZIP or just essentially clicking all the download buttons would be useful. Doing this in the chrome console isn't fun heh.

Font pack URL's in which a pack that includes multiple families being parsed would be useful too. (e.g. https://fonts.adobe.com/collections/spark-font-pack )

This is sort of two tickets in one but they relate to more relate to UX changes which I believe will be roughly in the same area of code.

**Comment by CodeZombie** [comment]
These are excellent suggestions, I'll look into adding these features soon.

**Comment by CodeZombie** [comment]
Added the ability to handle Font Collection URLs to Typerip.
Let me know if if you run into any problems with it.

I'm working on a Download All feature as well :)

**Comment by CodeZombie** [comment]
Download All is now implemented. A button appears at next to the font family/collection title allowing you to download the entire set of fonts as a ZIP.
