### ISSUE TITLE
403 Error

### ISSUE THREAD

**Issue by juanitolaguna** [CodeZombie/TypeRip#14]
Entering a the adobe font family link does not work anymore. Throws an 403.

"Failed to load resource: the server responded with a status of 403 (Forbidden)"

**Comment by CodeZombie** [comment]
Looks like the CORS proxy I was using has added a feature to remove automated tools from using it (like I'm doing)
I'll have to find a new proxy to use.

In the meantime, if you go to:

`https://cors-anywhere.herokuapp.com/corsdemo`

and click "Request temporary access to the demo server", it'll grant your machine access and Typerip will work again for some amount of time.

**Comment by CodeZombie** [comment]
The CORS proxy has been replaced with https://allorigins.win/, so this error should no longer occur.
