### ISSUE TITLE
Fonts are corrupt

### ISSUE THREAD

**Issue by schroef** [CodeZombie/TypeRip#16]
Tried adding some fonts to Suitcase and get a corrupt error. Not exactly sure what it is. Ill check with FontForge and see what this tells me

![corrupt-fonts-error](https://user-images.githubusercontent.com/6923008/122265836-2628cb00-cea7-11eb-9951-c4da82a78ba0.png)

**Comment by schroef** [comment]
When i try to open TTF fonts i get an notification about permission to edit. If i confirm and save as OTF i can load it without issues

**Comment by CodeZombie** [comment]
This was probably a result of the OpenType.js-based font rebuilder corrupting the font files.
The latest update has removed this code, so this should no longer be an issue.

Closing!

**Comment by schroef** [comment]
Thanks, ill check it again
