### ISSUE TITLE
A little poking around with URLs

### ISSUE THREAD

**Issue by Artellia** [CodeZombie/TypeRip#27]
did you know the letter used as the file name (just before the ?) makes a difference? there are a number of different permutations that are valid.

- a=(hyphen name, install locked, ttf/otf)
- m=(hash name, install locked, ttf/otf)
- d=(right name, installable, woff wrap of ttf/otf)
- i=(hyphen name, installable, eot)
- j=(hash name, installable, ttf/otf)
- l=(right name, installable, woff2 wrap of ttf/otf)
- o=(exact same file as 'd')
- p=(hyphen name, installable, ttf/otf)
(I just went back and noticed some files come down as ttf, others otf, likely depending on what the actual serverside file is.)
The "right name" as in the family name field in the font. Other name fields seem to be filled as originally intended ('d' & 'l')

I would definitely recommend using 'l' for all downloads. It seems to require no reprocessing at all.

"Hash" names look like a crypto hash. Hyphen names are just a dash. When downloading by hand 'd' would be offered as d.woff in the dialog box. When downloading via a webcopy app, it did not, but the program did pick up eot correctly, and decided to put bin on 'o'.

I'm attaching my download & record so you can see what sort of results I ran into. Though the record doesn't show it, I actually tried all letters, 'a' to 'z'. It only recorded downloaded files. Incidentally, 'n' returned a 500 error where all other missing letters returned a 404.

[pf.zip](https://github.com/CodeZombie/TypeRip/files/9542288/pf.zip)
[webcopy-origin.txt](https://github.com/CodeZombie/TypeRip/files/9542289/webcopy-origin.txt)

EDIT: Just checked the 'l' file in TypeRip (Chrome Devtools' Override). Changed "a?" to "l?" and ".ttf" to ".woff2" in typerip.js, checked "Download without processing" and I get a ZIP full of WOFF2 files that open in FontLab 8 without errors and have correct internal name metadata and are not copyright/install locked. They can literally be taken straight from the ZIP and dumped in a Wordpress font folder for immediate use.

EDIT_2: I... um... I came across something interesting... Pop this into your browser bar: https://fonts.adobe.com/fonts.json
Note: Poked at this a bit, it takes query strings just like the /fonts page, including page numbers. Works exactly like a json version of the page.

**Comment by CodeZombie** [comment]
I really can't thank you enough for this work.

It took me a while to implement your findings because part of my goal of this software is to have the files downloaded from TypeRip be natively installable without further conversion by the user. Because WOFF2 files are not natively installable on Windows, I needed to find some way to convert them in-browser, it basically required a full rewrite of the tool to get a javascript-based woff2_to_ttf converter working.

But now it's all finished and released and appears to be working _way_ better than any previous version.

Thank you again, Artellia!
