### ISSUE TITLE
Missing glyphs

### ISSUE THREAD

**Issue by epistularum** [CodeZombie/TypeRip#32]
It seems like every single Japanese font has missing glyphs, typically "一", very basic kanji meaning "one".

edit: Disabling the post-processing fixes the issue.

**Comment by CodeZombie** [comment]
This was a bug with the opentype.js-based font rebuilding code that I had written to fix font files. This code has since been removed. All fonts (including japanese fonts) should include their full glyph sets when downloaded with TypeRip.

Closing!
