### ISSUE TITLE
"Regular" weight fonts don't work

### ISSUE THREAD

**Issue by ghost** [CodeZombie/TypeRip#33]
When I download a font, they seem to work well (regular, italic, bold and bold italic show correctly on the Mac Font Book). However, when using them in Microsoft Word, LibreOffice Writer and other programs, the regular weight shows as the bold weight? Is as if the programs don't recognize the regular font weight.

**Comment by CodeZombie** [comment]
This appears to have been a problem with the OpenType.js-based font rebuilder that TypeRip was previously using to rebuild font files.
This code has since been removed, so this should no longer be an issue, but please open a new issue if it happens again.
