### ISSUE TITLE
Processing removes kerning and other font features

### ISSUE THREAD

**Issue by elmimmo** [CodeZombie/TypeRip#35]
Processing removes all kerning data and other “lookup tables” from the font, effectively destroying the font as it will not render as the designer intended and will lack typographic features that the designer built into the original font.

Verified with http://badnoise.net/TypeRip/ pointed at https://fonts.adobe.com/fonts/vendetta and opening the downloaded font with FontForge v.20230101 on macOS 13.4 (22F66) Ventura (installed via Homebrew) ▸ menu Element ▸ Font attribute ▸ Lookups. If the font was downloaded without processing, there will be GSUP (ligatures, alternate glyphs…) and GPOS (kerning pairs) lookup tables; if it was downloaded with processing, there will be none.

**Comment by CodeZombie** [comment]
Closing this as the latest update no longer needs to rebuild fonts, therefore this will no longer happen.
