### ISSUE TITLE
Only one weight/style per font can be installed at a time (Windows and Mac)

### ISSUE THREAD

**Issue by chadders404** [CodeZombie/TypeRip#36]
Tested on:
Windows 11 Pro
KB50030219 OS Build 22621.2283

Apple M1 MacBook Pro 
MacOS Ventura 13.1

Symptoms:

Fonts download and install as expected. However, only the last font to be installed works.

For example, if I install 3 fonts; Arial Regular, Arial Bold and finally Arial Italic, only Arial Italic will show up in the illustrator font options and display. If I then go back and reinstall Arial Bold, Arial Italic will cease to work and Arial Bold will work instead.

This limitation does not occur with different font families.

I had a look in the Font Book on my Mac and all three fonts seem to be installed, so I don't think they are installing over each other.

Is this by design?

<img width="1439" alt="Screenshot 2023-09-24 at 15 23 37" src="https://github.com/CodeZombie/TypeRip/assets/99815730/85388c43-2dfd-449e-bc83-daa75243a067">

**Comment by pierow2k** [comment]
@chadders404 - I've just given it a go on Illustrator 2023 and managed to install all five fonts from a family without a hitch. Just to mention, I'm using FontExplorer for font management – though I can't see that being the root of the issue you're describing.

With `Arial`, you could be running into conflicts because of other software. Are you having similar problems with other fonts?

![2023-09-24-Illustrator_Fonts](https://github.com/CodeZombie/TypeRip/assets/9472998/e4c2902a-4a93-4ae1-926c-4c201568aa51)

**Comment by chadders404** [comment]
> @chadders404 - I've just given it a go on Illustrator 2023 and managed to install all five fonts from a family without a hitch. Just to mention, I'm using FontExplorer for font management – though I can't see that being the root of the issue you're describing.
> 
> With `Arial`, you could be running into conflicts because of other software. Are you having similar problems with other fonts?
> 
> ![2023-09-24-Illustrator_Fonts](https://user-images.githubusercontent.com/9472998/270188465-e4c2902a-4a93-4ae1-926c-4c201568aa51.png)

Thanks for taking a look. Arial was a bad example, I used it because it was a font everyone is familiar with. It's definitely not just system fonts.

Here is a screen recorded demo on my Mac: https://we.tl/t-sM1eejy1Fh 

This is occuring with most fonts- however not _every_ font. I was able to install all the styles for Aktiv Grotesque family on Windows PC with no issues a few weeks ago, and I have been able to install two styles of the Clarendon URW font family but no more. I am almost always limited to one font per family. However, unlike Mac, Windows only keeps the first font to be installed and ignores any subsequent installations of the same family, whereas Mac always keeps the latest one to be installed. There doesn't seem to be any correlation with it being TTF or OTF or installing seperately or as a package. I cannot identify any consistency to the behaviour. Let me know if there's anything I should be trying.

I am using Chrome on both devices so I wonder if it has anything to do with that?

**Comment by oghaki** [comment]
Just wanted to mention, I've been having the same issue for while, I think I noticed around the time Windows 11 was release, or maybe before (I think it might have been a preview install prior to release).  At the time, I thought it was probably a bug with Windows, and I had also copied over and installed a huge number of fonts at the same time from my Windows 10 installation, using the built-in font installation / management, which made it seem more plausible.  I had also found someone describing something similar on a forum discussing issues with Windows 11, so I was even less suspicious, the problems with the fonts never went away.  Eventually, I decided to clear them all out and re-install to no avail, so I started installing one family at a time, then individual styles, and the issue always persisted.  I seem to remember it being the same that the same style ended up being the usable one, regardless of what order I installed them in, but I'm not certain on that.  

Does anyone have any suggestions to try to test / troubleshoot?  This would be awesome, but almost all of the fonts I downloaded are basically unusable.

**Comment by zagdrath** [comment]
I am having the same issue on the latest version on Windows 11.

**Comment by tungwoodboi** [comment]
try my fix: https://typerip.htdesignz.net/

**Comment by CodeZombie** [comment]
This should be fixed now thanks to @tungwoodboi's fix. 
Please open a new issue if it keeps happening!
