### ISSUE TITLE
Doesn't seem to be working anymore - keeps giving me 'Request Failed Network Error'

### ISSUE THREAD

**Issue by MichaelH12345** [CodeZombie/TypeRip#49]
Whenever I have tried to use the site in the past few days, it just saying 'Request Failed Network Error' a second or 2 after entering the font URL. Could this be because maybe Adobe changed the way demo fonts are accessed or something???
Hope the site works soon as it's great and I'm trying to download a font family.

**Comment by CodeZombie** [comment]
This could have been related to #51. 
I had some bad logic checking the validity of responses from CORS proxies.
I've changed the logic to be more flexible and added two new CORS proxies which might give you better results. Could you retry a few times and let me know if things still aren't working?

Thank you!
