### ISSUE TITLE
Other languages

### ISSUE THREAD

**Issue by dusttier** [CodeZombie/TypeRip#5]
Thanks for this awesome riper)
May be you have any idea how to download font wirh all characters? (russian for exapmle).
I think need some tweeks in this place:
https://use.typekit.net/pf/tk/" + subfont_web_id + "/" + subfont_fvd + "/m?primer=" + font_primer + 
var font_primer always equals json.textSampleData.textSamplePrimers.en = "2f933ade0879e52e3bcd40ae1192d21e9abf39f5672f029a05c1e05c6605ecf0"  for all fonts.
Is it a coded character set (range A-B, a-b, 0-9)?
can we encode a larger range that will include other languages?

**Comment by CodeZombie** [comment]
Your suggested tweak was pretty much exactly what needed to be done. The tool now checks which language the font is made for, and grabs the primer listed for that language.
Additionally, it now uses a text sample in that language, as opposed to lorum ipsum.

This also fixed #4 

Thanks for raising the issue and the great suggestion.
