### ISSUE TITLE
Request Failed:  Request failed with status code 404

### ISSUE THREAD

**Issue by sawazbaabe** [CodeZombie/TypeRip#51]
Hello folks, 

everytime when I try to download some fonts I'll get "Request Failed
Request failed with status code 404" as a response. Is there any workarounds or something else?

**Comment by taretare666** [comment]
Same issue here, been trying to download any font from 4 hours ago now

**Comment by DesolateHawk1** [comment]
Funnily enough, I just found this gem, but it’s not working shows a "404 code."

**Comment by CodeZombie** [comment]
Looks like the primary CORS proxy I was using, `https://corsproxy.io/?` returns an adobe fonts `404` page even when you submit a valid URL. Not sure why that is, could be an out-of-date cache on their end, or Adobe intentionally blacklisted requests from that domain.

Either way, I added some new proxies to the proxy list and added some logic that avoids this problem in the future.

Refresh the TypeRip page and try again a few times (it may take a couple attempts for the changes to kick in), and it should start working now. Let me know if anything is still broken!
