### ISSUE TITLE
Long numeric font names (in metadata)

### ISSUE THREAD

**Issue by hrvstr** [CodeZombie/TypeRip#8]
Is there any software to correct the font name (metadata) after downloading? GUI or CLI does not matter really.

The name of the files is correct but after importing them to Font Book App on Mac they show up as long numeric names.

E.g.:  "31d8439d73a53420631b6427a6c5b5d2f7f9f77028033b1302d6d2951c5a95cb"

**Comment by hrvstr** [comment]
I figured it out:

You can change the font name using these tools: 
https://github.com/chrissimpkins/fontname.py
https://github.com/fonttools/fonttools

**Comment by pierow2k** [comment]
Thanks for pointing out these tools @hrvstr 
I had the same question and [fontname](https://github.com/chrissimpkins/fontname.py) looks like it should do the trick.

**Comment by CodeZombie** [comment]
The latest commit has finally fixed this problem. Let me know if you run into any new problems with it.
