### ISSUE TITLE
Download Button not working

### ISSUE THREAD

**Issue by scysys** [CodeZombie/TypeRip#9]
<img width="295" alt="Bildschirmfoto 2019-12-05 um 12 28 57" src="https://user-images.githubusercontent.com/1695531/70231568-df5b0080-175a-11ea-8050-e6763dd23b18.png">

**Comment by CodeZombie** [comment]
Which font were you trying to download when this happened?

**Comment by scysys** [comment]
This one: https://fonts.adobe.com/fonts/aller

**Comment by scysys** [comment]
![Bildschirmfoto 2019-12-10 um 13 05 53](https://user-images.githubusercontent.com/1695531/70528164-d6e53a00-1b4d-11ea-8420-cf7899b315aa.png)

**Comment by swiinger** [comment]
Same problem with https://fonts.adobe.com/fonts/jaf-domus
Thank you

**Comment by RichieRoo101** [comment]
Great work, but yes. I experienced the same issue with:
https://fonts.adobe.com/fonts/benton-sans

**Comment by CodeZombie** [comment]
This problem was due to Opentype.js (The library used to re-encode fonts and 'fix' them), not being able to handle anything but perfectly formatted font data.

All the fonts mentioned in this issue (and others with the same type of problem) should now work.
